<?php
$_htmlId      = $this->getElement()->getHtmlId();
$_htmlClass   = $this->getElement()->getClass();
$_htmlName    = $this->getElement()->getName();
$_readonly    = $this->getElement()->getReadonly();
$collection = [];
$_counter = 0;
$select = ['A', 'B', 'C', 'D'];
$types = ['price', 'name', 'code'];
$optionsLetter = '';
$optionsTypes = '';
foreach ($select as $key => $value) {
    $optionsLetter .= "<option value=". $key . ">" . $value . "</option>";
}
foreach ($types as $key => $value) {
    $optionsTypes .= "<option value=". $key . ">" . $value . "</option>";
}
?>


<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td colspan="10" class="config">
        <table id="attribute-options-table" class="dynamic-grid pricelists-config" cellspacing="0" cellpadding="0" border="0" style="border: none">
            <tr>
                <th><?php echo $this->__('Column') ?></th>
                <th><?php echo $this->__('Type') ?></th>
                <th><button id="add_new_option_button" title="Add Option" type="button" class="scalable add"><span><span><span><?php echo $this->__('Add Option') ?></span></span></span></button></th>
            </tr>
            <?php foreach ($collection as $_item): ?>
                <tr class="option-row pricelists-config-dayrow" id="config-row-<?php echo $_counter?>">
                    <td><input name="<?php echo $_htmlName; ?>[option_<?php echo $_counter ?>][closingconfig]" class="input-text" type="text"></td>
                    <td><input name="<?php echo $_htmlName; ?>[option_<?php echo $_counter ?>][sortorder]" class="input-text" type="text"></td>
                    <td class="a-left" id="delete_button_container_option_<?php echo $_counter ?>'">
                        <input name="<?php echo $_htmlName; ?>[option_<?php echo $_counter ?>][id]" type="hidden">
                        <input id="delete-row-<?php echo $_counter ?>" type="hidden" class="delete-flag" name="<?php echo $_htmlName; ?>[delete][option_<?php echo $_counter ?>]" value=""/>
                        <button onclick="$('config-row-<?php echo $_counter ?>').style.display='none'; $('delete-row-<?php echo $_counter ?>').setValue(1);" title="Delete" type="button" class="scalable delete delete-option"><span><span><span>Delete</span></span></span></button>
                    </td>
                </tr>
                <?php
                $_counter++;
            endforeach;
            ?>
        </table>
        <script type="text/javascript">//<![CDATA[
            var _form_html_row = '' +
                '<tr class="option-row pricelists-config-dayrow" id="config-row-{{id}}">' +
                    '<td>' +
                        '<select name="<?php echo $_htmlName; ?>[value][option_{{id}}][column]"><?= $optionsLetter; ?></select>' +
                    '</td>' +
                    '<td>' +
                        '<select name="<?php echo $_htmlName; ?>[value][option_{{id}}][letter]" class="input-text"><?= $optionsTypes; ?></select>' +
                    '</td>' +
                    '<td class="a-left" id="delete_button_container_option_{{id}}">'+
                        '<input name="<?php echo $_htmlName; ?>[value][option_{{id}}][id]" value="" type="hidden">'+
                        '<input id="delete-row-{{id}}" type="hidden" class="delete-flag" name="<?php echo $_htmlName; ?>[delete][option_{{id}}]" value=""/>'+
                        '<button onclick="$(\'config-row-{{id}}\').style.display=\'none\'; $(\'delete-row-{{id}}\').setValue(1);" title="Delete" type="button" class="scalable delete delete-option">' +
                            '<span>' +
                                '<span>' +
                                    '<span>Delete</span>' +
                                '</span>' +
                            '</span>' +
                        '</button>' +
                    '</td>' +
                '</tr>';

            var _pricelists_counter = <?php echo $_counter?>;

            $('add_new_option_button').observe('click', function(){
                $('attribute-options-table').insert(_form_html_row.replace(/\{\{id\}\}/ig, _pricelists_counter));
                _pricelists_counter++;
            });

            //]]></script>
    </td>
</tr>
