<?php

class Stableflow_Pricelists_Block_Adminhtml_Preview extends Mage_Adminhtml_Block_Template {

    protected function _construct() {
        parent::_construct(); // TODO: Change the autogenerated stub

        $this->setTemplate('stableflow/pricelists/preview.phtml');
    }
}